const cardBase = {
  ace: { value: 11, alternativeValue: 1 },
  two: { value: 2 },
  three: { value: 3 },
  four: { value: 4 },
  five: { value: 5 },
  six: { value: 6 },
  seven: { value: 7 },
  eight: { value: 8 },
  nine: { value: 9 },
  ten: { value: 10 },
  jack: { value: 12, alternativeValue: 2 },
  queen: { value: 13, alternativeValue: 3 },
  king: { value: 14, alternativeValue: 4 },
};

const cards = {
  'ace-clubs': { ...cardBase.ace },
  'ace-diamonds': { ...cardBase.ace },
  'ace-hearts': { ...cardBase.ace },
  'ace-spades': { ...cardBase.ace },
  'two-clubs': { ...cardBase.two },
  'two-diamonds': { ...cardBase.two },
  'two-hearts': { ...cardBase.two },
  'two-spades': { ...cardBase.two },
  'three-clubs': { ...cardBase.three },
  'three-diamonds': { ...cardBase.three },
  'three-hearts': { ...cardBase.three },
  'three-spades': { ...cardBase.three },
  'four-clubs': { ...cardBase.four },
  'four-diamonds': { ...cardBase.four },
  'four-hearts': { ...cardBase.four },
  'four-spades': { ...cardBase.four },
  'five-clubs': { ...cardBase.five },
  'five-diamonds': { ...cardBase.five },
  'five-hearts': { ...cardBase.five },
  'five-spades': { ...cardBase.five },
  'six-clubs': { ...cardBase.six },
  'six-diamonds': { ...cardBase.six },
  'six-hearts': { ...cardBase.six },
  'six-spades': { ...cardBase.six },
  'seven-clubs': { ...cardBase.seven },
  'seven-diamonds': { ...cardBase.seven },
  'seven-hearts': { ...cardBase.seven },
  'seven-spades': { ...cardBase.seven },
  'eight-clubs': { ...cardBase.eight },
  'eight-diamonds': { ...cardBase.eight },
  'eight-hearts': { ...cardBase.eight },
  'eight-spades': { ...cardBase.eight },
  'nine-clubs': { ...cardBase.nine },
  'nine-diamonds': { ...cardBase.nine },
  'nine-hearts': { ...cardBase.nine },
  'nine-spades': { ...cardBase.nine },
  'ten-clubs': { ...cardBase.ten },
  'ten-diamonds': { ...cardBase.ten },
  'ten-hearts': { ...cardBase.ten },
  'ten-spades': { ...cardBase.ten },
  'queen-clubs': { ...cardBase.queen },
  'queen-diamonds': { ...cardBase.queen },
  'queen-hearts': { ...cardBase.queen },
  'queen-spades': { ...cardBase.queen },
  'king-clubs': { ...cardBase.king },
  'king-diamonds': { ...cardBase.king },
  'king-hearts': { ...cardBase.king },
  'king-spades': { ...cardBase.king },
  jack15: { value: 15 },
  jack20: { value: 20 },
  jack30: { value: 30 },
  jack35: { value: 35 },
};

export default cards;
